isProd: false

server:
  port: 8086

my:
  swagger:
    prefix:

spring:
  application:
    name: prediction-catalogue
  datasource:
    url: jdbc:postgresql://ec2-52-212-157-46.eu-west-1.compute.amazonaws.com:5432/dri28cqu7nseu
    username: huvvyzqwjkioeh
    password: d8a15aeeaac6d8c0cb4431c343584c3f19bfda74054d44fdb7dba2a1cb0b7dab
    driverClassName: org.postgresql.Driver
    initialize: true
    initialization-mode: always
    hikari:
      connectionTimeout: 200000
      maximumPoolSize: 10
      idle-timeout: 300000
      minimum-idle: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    jpa:
      repositories:
        bootstrap_mode: default
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

# Show details of health endpoint
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    diskspace:
      enabled: true
    db:
      enabled: true

---
spring:
  profiles: prod

my:
  swagger:
    prefix: /prediction-catalogue

isProd: true