apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-catalogue-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prediction-catalogue
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: prediction-catalogue
    spec:
      containers:
        - image: blarc/rso-prediction-catalogue
          name: prediction-catalogue
          ports:
            - containerPort: 8086
              name: server
              protocol: TCP
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: server
            initialDelaySeconds: 90
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: server
            initialDelaySeconds: 90
            periodSeconds: 3
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prediction-catalogue-db-password
                  key: spring_datasource_password
---

apiVersion: v1
kind: Service
metadata:
  name: prediction-catalogue
spec:
  type: ClusterIP
  ports:
    - port: 8086
      protocol: TCP
      targetPort: server
  selector:
    app: prediction-catalogue